Add function to cast `interface{}` to `[]float64`
spf13/cast pull request #179
Opened 2023-03-06 16:13 UTC by ste93cry

Fixes #176 by adding the `ToFloat64Slice()` and `ToFloat64SliceE()` helper functions.

2023-03-06 16:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/spf13/cast?pullRequest=179) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/spf13/cast?pullRequest=179) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/spf13/cast?pullRequest=179) it.</sub>

2023-08-08 07:35 UTC, twz915 commented
I need this feature

2024-04-01 12:18 UTC, HiCheems commented
Is there any plan to add this function?

2025-04-12 12:00 UTC, sagikazarmark requested changes
Could you please rebase your PR and use the new generic functions? Thanks!

2025-04-12 12:01 UTC, sagikazarmark commented
Overlaps with #236

2025-04-12 17:13 UTC, ste93cry commented
>Could you please rebase your PR and use the new generic functions? Thanks!

Done, I hope the changes are what you intended

2025-04-13 10:49 UTC, sagikazarmark approved these changes
Thanks!

2025-04-13 10:51 UTC, merged